version: "3.9"

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:18
    user: "1000:1000"
    container_name: odoo18-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons:rw
      - ./config:/etc/odoo
      - ./data:/var/lib/odoo
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: odoo18-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ODOO_PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${ODOO_PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

